### ISSUE TITLE
PA Review: Reviews

### ISSUE THREAD

**Issue by KSilberblatt** [KSilberblatt/breezelnl#5]
- [x] Users can see and review spots
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by wongshington** [comment]
- [x] if i make a review it submits just fine, but if i try to submit a review afterwards when the review input field is supposedly empty it just sends a duplicate review
- [x] if i write a review, but don't select a star count, it assigns the same star count from the most recent review that i left
- [x] for both of the previous ones it might be a two birds with one stone fix, don't forget to reset the state
- [x] add a little space between the user name and the stars
