### ISSUE TITLE
PA review: bookings

### ISSUE THREAD

**Issue by KSilberblatt** [KSilberblatt/breezelnl#6]
- [x] Users (and demo user) can book available spots
- [x] Bookings can be seen by the user
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds to demonstrate the feature

**Comment by wongshington** [comment]
- [x] font size a little bigger on the "your bookings" link
- [x] maybe add an icon next to the link as well to add some "flavor"
